#pragma config(Sensor, in1,    accx,           sensorAccelerometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		writeDebugStreamLine("AccX %d", SensorValue[accx]);
	}
}
