#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           rback,         tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           lback,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port8,           rfront,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port9,           lfront,        tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*bLCDBacklight = true;
	while(1){
		clearLCDLine(0);
		displayLCDString(1, 2, "Hello World ");
	}*/

	// X, Y Joystick

	/*while(1){
		writeDebugStreamLine("X: %d, Y: %d",vexRT[Ch1],vexRT[Ch2]);
		wait(0.01);
	}*/

	// Joystick Button
	/*while(1){
		writeDebugStreamLine("X: %d, Y: %d",vexRT[Btn7L],vexRT[Btn7R]);
		wait(0.05);
	}*/
	while(1){
		setMotor(rback,vexRT[Ch3]);
		setMotor(lback,vexRT[Ch3]);
		setMotor(rfront,vexRT[Ch3]);
		setMotor(lfront,vexRT[Ch3]);
	}
}
