#pragma config(Sensor, dgtl7,  led1,           sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		turnLEDOn(led1);
		wait(1);
		turnLEDOff(led1);
		wait(1);
	}
}
