#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftlift,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightlift,      sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           lmobile,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rwheels,       tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           lwheels,       tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port4,           ltlift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rtlift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lblift,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_5)
#pragma config(Motor,  port7,           rblift,        tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port8,           flip,          tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rmobile,       tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Timer Note:
// T1 : PID Controller
// T2 : Lift Speed limiter

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                             Utility Function                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/


int min(int a, int b){
	return a<b?a:b;
}

int max(int a, int b){
	return a>b?a:b;
}

int bound(int x, int a, int b){
	return max(a,min(x,b));
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  definitiona and variables for the motor slew rate controller.              */
/*  https://www.vexforum.com/index.php/6146-robotc-programming-tips/p2#p53799  */
/*-----------------------------------------------------------------------------*/

#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 10      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        15      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10

// Array to hold requested speed for the motors
int motorReq[ MOTOR_NUM ];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current motor speed.
int motorSlew[ MOTOR_NUM ];

task MotorSlewRateTask()
{
    int motorIndex;
    int motorTmp;

    // Initialize stuff
    for(motorIndex=0;motorIndex<MOTOR_NUM;motorIndex++)
        {
        motorReq[motorIndex] = 0;
        motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
        }

    // run task until stopped
    while( true )
        {
        // run loop for every motor
        for( motorIndex=0; motorIndex<MOTOR_NUM; motorIndex++)
            {
            // So we don't keep accessing the internal storage
            motorTmp = motor[ motorIndex ];

            // Do we need to change the motor value ?
            if( motorTmp != motorReq[motorIndex] )
                {
                // increasing motor value
                if( motorReq[motorIndex] > motorTmp )
                    {
                    motorTmp += motorSlew[motorIndex];
                    // limit
                    if( motorTmp > motorReq[motorIndex] )
                        motorTmp = motorReq[motorIndex];
                    }

                // decreasing motor value
                if( motorReq[motorIndex] < motorTmp )
                    {
                    motorTmp -= motorSlew[motorIndex];
                    // limit
                    if( motorTmp < motorReq[motorIndex] )
                        motorTmp = motorReq[motorIndex];
                    }

                // finally set motor
                motor[motorIndex] = motorTmp;
                }
            }

        // Wait approx the speed of motor update over the spi bus
        wait1Msec( MOTOR_TASK_DELAY );
        }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              PID Controller                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#define PIDC 5
#define DEADBAND 100
#define PID_TASK_DELAY 30
#define MIN_LIFT 200

float kp[10],ki[10],kd[10];
int lastE[10];
float lastI[10];
int target[10];
int pido[10];
int rpos[10];
int lim[10];

void updatePID(){
	int tdiff = time1[T1];

	if(tdiff>=DEADBAND){
		for(int ch = 0; ch < PIDC; ch++){
			float ci, cd, sum;
			int et;
			//calculate error
			et = target[ch]-rpos[ch];
			// "i" and "d"
			cd = (et-lastE[ch])/(float)tdiff;
			// calculate I term + something that I forgot the name lol
			if(-150<et&&et<150&&et!=0){
				ci = lastI[ch] + (lastE[ch]+et)/2.0*tdiff;
			}else{
				ci = 0;
			}

			lastE[ch] = et;
			lastI[ch] = ci;
			sum = kp[ch]*et + ki[ch]*ci + kd[ch]*cd;

			pido[ch] = bound((int)sum,-lim[ch],lim[ch]);
		}
		clearTimer(T1);
	}
}

// Ch0 = Right lift
// Ch1 = Left lift
// Ch2 = Right Wheel
// Ch3 = Left Wheel
void UpdateMovement(){
	//update encoder value
	rpos[0] = nMotorEncoder[rblift];
	rpos[1] = nMotorEncoder[lblift];

	//recalculate PID
	updatePID();

	//update motor value
	//motorReq[rblift] = pido[0];
	//motorReq[rtlift] = pido[0];
	//motorReq[lblift] = pido[1];
	//motorReq[ltlift] = pido[1];
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                         Specific Movement Code                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

int liftOrigin;
bool isFlipRect;
bool isMobileOut;

void pickMobile(){
	if(isMobileOut){
		while(nMotorEncoder[rmobile]<700&&!vexRT[Btn7L]){
			motorReq[rmobile] = -128;
			motorReq[lmobile] = -128;
		}
		motorReq[rmobile] = 0;
		motorReq[lmobile] = 0;
	}else{
		while(nMotorEncoder[rmobile]>50&&!vexRT[Btn7L]){
			motorReq[rmobile] = 128;
			motorReq[lmobile] = 128;
		}
		motorReq[rmobile] = 0;
		motorReq[lmobile] = 0;
	}
	isMobileOut = !isMobileOut;
}

void pickCone(){
	if(isFlipRect){
		while(nMotorEncoder[flip]<430&&!vexRT[Btn7L]){
			motorReq[flip] = 128;
		}
		motorReq[flip] = 0;
		motorReq[claw] = -80;
	}else{
		while(nMotorEncoder[flip]>40&&!vexRT[Btn7L]){
			motorReq[flip] = -128;
		}
		motorReq[flip] = 0;
		motorReq[claw] = 80;
		wait(0.2);
		motorReq[claw] = 0;
	}
	isFlipRect = !isFlipRect;
}

void liftUp(){
	int newPos = liftOrigin+time1[T2]/3;
	newPos = bound(newPos, 200, 1000);
	target[0] = newPos;
	target[1] = newPos;
}

void liftDown(){
	int newPos = liftOrigin-time1[T2]/3;
	newPos = bound(newPos, 200, 1000);
	target[0] = newPos;
	target[1] = newPos;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                         Specific Movement Code                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

	// stop all task
	//stopAllTasks();

  // reset PID
  for(int i = 0; i < PIDC; i++){
		lastE[i] = 0.0;
		lastI[i] = 0.0;
		target[i] = 0;
		pido[i] = 0;
		rpos[i] = 0;
	}
	// config all cons
	// Ch0 = Right lift
	kp[0] = 1.3;
	kd[0] = 40;
	ki[0] = 0.000;
	lim[0] = 100;

	// Ch1 = Left lift
	kp[1] = 1.5;
	kd[1] = 50;
	ki[1] = 0.000;
	lim[1] = 100;

	// Reset lift and flip
	motor[rblift] = -30;
	motor[rtlift] = -30;
	motor[lblift] = -30;
	motor[ltlift] = -30;
	motor[flip] = -30;
	wait(1);
	motor[rblift] = 0;
	motor[rtlift] = 0;
	motor[lblift] = 0;
	motor[ltlift] = 0;
	motor[flip] = 0;

	// Reset encoder
	nMotorEncoder[lwheels] = 0;
	nMotorEncoder[rwheels] = 0;
	nMotorEncoder[flip] = 0;
	nMotorEncoder[rblift] = 0;
	nMotorEncoder[lblift] = 0;

	liftOrigin = MIN_LIFT;
	isFlipRect = true;
	isMobileOut = true;
	//target[0] = target[1] = MIN_LIFT;

	clearTimer(T1);
	clearTimer(T2);

	// restart all task
	startTask( MotorSlewRateTask );

	// Reset mobile
	//wait(1);
	//motorReq[rmobile] = 40;
	//motorReq[lmobile] = 40;
	//wait(1);
	//motorReq[rmobile] = 0;
	//motorReq[lmobile] = 0;

	nMotorEncoder[rmobile] = 0;
}



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void resetWheels(){
	nMotorEncoder[rwheels] = 0;
	nMotorEncoder[lwheels] = 0;
}

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................
	/*
  // 90 turn
	resetWheels();
  while(nMotorEncoder[rwheels]<500){
  	motorReq[rwheels] = 100;
  	motorReq[lwheels] = -100;
	}

  // walk front
	resetWheels();
	while(nMotorEncoder[rwheels]<500){
  	motorReq[rwheels] = 100;
  	motorReq[lwheels] = 100;
	}

	// 45 turn
	resetWheels();
  while(nMotorEncoder[rwheels]<500){
  	motorReq[rwheels] = -100;
  	motorReq[lwheels] = 100;
	}*/

	// walk front
	AutonomousCodePlaceholderForTesting();

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	pre_auton();

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

  	// Tank Drive
  	motorReq[lwheels] = vexRT[Ch3]*0.65;
  	//motorReq[lblift] = vexRT[Ch3];
		//motorReq[ltlift] = vexRT[Ch3];

  	motorReq[rwheels] = vexRT[Ch2]*0.65;

  	// Lift up, down
  	if(vexRT[Btn5U]){
  		//go up
  		motorReq[rblift] = 100;
			motorReq[rtlift] = 100;
			motorReq[lblift] = 100;
			motorReq[ltlift] = 100;
  	}else if(vexRT[Btn5D]){
  		//go down
  		motorReq[rblift] = -100;
			motorReq[rtlift] = -100;
			motorReq[lblift] = -100;
			motorReq[ltlift] = -100;
  	}else{
  		motorReq[rblift] = 0;
			motorReq[rtlift] = 0;
			motorReq[lblift] = 0;
			motorReq[ltlift] = 0;
  	}

  	// Mobile goal : Automatic Mode
  	if(vexRT[Btn6D]){
  		pickCone();
  	}
  	// Mobile goal : Manual Mode
  	if(vexRT[Btn7U]){
  		motorReq[rmobile] = 128;
			motorReq[lmobile] = 128;
  	}else if(vexRT[Btn7D]){
  		motorReq[rmobile] = -128;
			motorReq[lmobile] = -128;
  	}else{
  		motorReq[rmobile] = 0;
			motorReq[lmobile] = 0;
  	}

  	// Pickup Cone : Automatic Mode
  	if(vexRT[Btn6U]){
  		pickCone();
  	}
		// Pickup Cone : Manual Mode
  	if(vexRT[Btn8U]){
  		motorReq[claw] = -80;
  	}else if(vexRT[Btn8D]){
  		motorReq[claw] = 80;
  	}else{
  		motorReq[claw] = 0;
  	}

  	if(vexRT[Btn8L]){
  		motorReq[flip] = -128;
  	}else if(vexRT[Btn8R]){
  		motorReq[flip] = 128;
  	}else{
  		motorReq[flip] = 0;
  	}

		//if(vexRT[Btn7L]){
  		//motorReq[lblift] = 70;
			//motorReq[ltlift] = 70;
  	//}
  	//if(vexRT[Btn7R]){
  		//motorReq[rblift] = 70;
			//motorReq[rtlift] = 70;
  	//}

		UpdateMovement();
  	writeDebugStreamLine("Encoder D:%d (T.%d) R:(R.%d P.%d) L:(R.%d P.%d)", kd[0], target[0], rpos[0], pido[0], rpos[1], pido[1]);
  }
}
