#pragma config(Sensor, in1,    ,               sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*while(1){
		if(SensorValue[dgtl2]==1){
			setMotor(port1,30);
		}else{
			stopMotor(port1);
		}
	}*/
	//writeDebugStreamLine("Encoder Value %d", SensorValue[dgtl3]);
	/*SensorValue[dgtl3] = 0;
	while(SensorValue[dgtl3]<=360){
		setMotor(port1,100);
	}
	writeDebugStreamLine("Encoder Value %d", SensorValue[dgtl3]);
	setMotor(port1,-450);
	wait(0.1);
	stopMotor(port1);
	wait(1);
	writeDebugStreamLine("Encoder Value %d", SensorValue[dgtl3]);*/
	SensorValue[in1] = 0;
	while(1){
		writeDebugStreamLine("Gyro Value %d %d", SensorValue[in1],SensorValue[in1]%360);
		wait(0.1);
	}

}
