#pragma config(Motor,  port2,           rback,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lback,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rfront,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lfront,        tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1){
	setMotor(lfront,-vexRT[Ch3]);
	setMotor(rfront,vexRT[Ch3]);
	SetMotor(lback,-vexRT[Ch3]);
	SetMotor(rback,vexRT[Ch3]);
}

}
